package com.example.docpro.features.user;

public enum UserSpecialization {

  NEUROLOGIE,
  OFTALMOLOGIE,
  PEDIATRIE,
  ORTOPEDIE,
  MEDICINA_INTERNA,
  ENDOCRINOLOGIE,
  CHIRURGIE,
  ALERGOLOGIE,
  GASTROENTROLOGIE,
  CARDIOLOGIE,
  ORL,
  UROLOGIE,
  MEDICINA_MUNCII
}
